const data = {
  products: [
    {
      _id: "1",
      name: "Nike Shoes",
      slug: "nike-shoes",
      category: "Footwear",
      image: "http://localhost:3000/images/product1.jpg",
      price: 150,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 15,
      description: "high quality footwear",
    },
    {
      _id: "2",
      name: "Adidas Pants",
      slug: "adidas-pants",
      category: "Pants",
      image: "http://localhost:3000/images/product2.jpg",
      price: 45,
      countInStock: 50,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 30,
      description: "high quality footwear",
    },
    {
      _id: "3",
      name: "Timex Watch",
      slug: "timex-watch",
      category: "Watch",
      image: "http://localhost:3000/images/product3.jpg",
      price: 10000,
      countInStock: 10,
      brand: "Timex",
      rating: 5,
      numReviews: 5,
      description: "high quality watch",
    },
    {
      _id: "4",
      name: "Converse Shoes",
      slug: "converse shoes",
      category: "Footwear",
      image: "http://localhost:3000/images/product4.jpg",
      price: 80,
      countInStock: 20,
      brand: "Converse",
      rating: 4,
      numReviews: 25,
      description: "high quality footwear",
    },
    {
      _id: "5",
      name: "Saucony Shoes",
      slug: "saucony-shoes",
      category: "Footwear",
      image: "http://localhost:3000/images/product5.jpg",
      price: 100,
      countInStock: 0,
      brand: "Saucony",
      rating: 5,
      numReviews: 10,
      description: "high quality footwear",
    },
    {
      _id: "6",
      name: "New Balance Shirt",
      slug: "new-balance-shirt",
      category: "Shirt",
      image: "http://localhost:3000/images/product6.jpg",
      price: 50,
      countInStock: 40,
      brand: "New Balance",
      rating: 4,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};

export default data;
